<?php

/**
 * BaseShowmobileDriver
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $vehicle_id
 * @property integer $event_id
 * @property sfGuardUser $User
 * @property ShowmobileEvent $Event
 * @property ShowmobileVehicle $Vehicle
 * @property Doctrine_Collection $ShowmobilePassenger
 * 
 * @method integer             getUserId()              Returns the current record's "user_id" value
 * @method integer             getVehicleId()           Returns the current record's "vehicle_id" value
 * @method integer             getEventId()             Returns the current record's "event_id" value
 * @method sfGuardUser         getUser()                Returns the current record's "User" value
 * @method ShowmobileEvent     getEvent()               Returns the current record's "Event" value
 * @method ShowmobileVehicle   getVehicle()             Returns the current record's "Vehicle" value
 * @method Doctrine_Collection getShowmobilePassenger() Returns the current record's "ShowmobilePassenger" collection
 * @method ShowmobileDriver    setUserId()              Sets the current record's "user_id" value
 * @method ShowmobileDriver    setVehicleId()           Sets the current record's "vehicle_id" value
 * @method ShowmobileDriver    setEventId()             Sets the current record's "event_id" value
 * @method ShowmobileDriver    setUser()                Sets the current record's "User" value
 * @method ShowmobileDriver    setEvent()               Sets the current record's "Event" value
 * @method ShowmobileDriver    setVehicle()             Sets the current record's "Vehicle" value
 * @method ShowmobileDriver    setShowmobilePassenger() Sets the current record's "ShowmobilePassenger" collection
 * 
 * @package    showmobile
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShowmobileDriver extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('showmobile_driver');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('ShowmobileEvent as Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('ShowmobileVehicle as Vehicle', array(
             'local' => 'vehicle_id',
             'foreign' => 'id'));

        $this->hasMany('ShowmobilePassenger', array(
             'local' => 'id',
             'foreign' => 'driver_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}