<?php

/**
 * BaseShowmobileBand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $bio
 * @property string $img
 * @property string $logo
 * @property string $url
 * @property string $email
 * @property integer $zone_id
 * @property Doctrine_Collection $Events
 * @property Doctrine_Collection $EventBands
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getBio()        Returns the current record's "bio" value
 * @method string              getImg()        Returns the current record's "img" value
 * @method string              getLogo()       Returns the current record's "logo" value
 * @method string              getUrl()        Returns the current record's "url" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method integer             getZoneId()     Returns the current record's "zone_id" value
 * @method Doctrine_Collection getEvents()     Returns the current record's "Events" collection
 * @method Doctrine_Collection getEventBands() Returns the current record's "EventBands" collection
 * @method ShowmobileBand      setName()       Sets the current record's "name" value
 * @method ShowmobileBand      setBio()        Sets the current record's "bio" value
 * @method ShowmobileBand      setImg()        Sets the current record's "img" value
 * @method ShowmobileBand      setLogo()       Sets the current record's "logo" value
 * @method ShowmobileBand      setUrl()        Sets the current record's "url" value
 * @method ShowmobileBand      setEmail()      Sets the current record's "email" value
 * @method ShowmobileBand      setZoneId()     Sets the current record's "zone_id" value
 * @method ShowmobileBand      setEvents()     Sets the current record's "Events" collection
 * @method ShowmobileBand      setEventBands() Sets the current record's "EventBands" collection
 * 
 * @package    showmobile
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShowmobileBand extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('showmobile_band');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('bio', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('img', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('logo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('zone_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShowmobileEvent as Events', array(
             'refClass' => 'ShowmobileEventBand',
             'local' => 'showmobile_band_id',
             'foreign' => 'showmobile_event_id'));

        $this->hasMany('ShowmobileEventBand as EventBands', array(
             'local' => 'id',
             'foreign' => 'showmobile_band_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}