<?php

/**
 * BaseShowmobileAddressBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property string $street
 * @property string $suburb
 * @property string $city
 * @property integer $zone_id
 * @property string $postal_code
 * @property ShowmobileZone $Zone
 * @property Doctrine_Collection $ShowmobileVenue
 * @property Doctrine_Collection $sfGuardUserProfile
 * 
 * @method string                getLabel()              Returns the current record's "label" value
 * @method string                getStreet()             Returns the current record's "street" value
 * @method string                getSuburb()             Returns the current record's "suburb" value
 * @method string                getCity()               Returns the current record's "city" value
 * @method integer               getZoneId()             Returns the current record's "zone_id" value
 * @method string                getPostalCode()         Returns the current record's "postal_code" value
 * @method ShowmobileZone        getZone()               Returns the current record's "Zone" value
 * @method Doctrine_Collection   getShowmobileVenue()    Returns the current record's "ShowmobileVenue" collection
 * @method Doctrine_Collection   getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" collection
 * @method ShowmobileAddressBook setLabel()              Sets the current record's "label" value
 * @method ShowmobileAddressBook setStreet()             Sets the current record's "street" value
 * @method ShowmobileAddressBook setSuburb()             Sets the current record's "suburb" value
 * @method ShowmobileAddressBook setCity()               Sets the current record's "city" value
 * @method ShowmobileAddressBook setZoneId()             Sets the current record's "zone_id" value
 * @method ShowmobileAddressBook setPostalCode()         Sets the current record's "postal_code" value
 * @method ShowmobileAddressBook setZone()               Sets the current record's "Zone" value
 * @method ShowmobileAddressBook setShowmobileVenue()    Sets the current record's "ShowmobileVenue" collection
 * @method ShowmobileAddressBook setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" collection
 * 
 * @package    showmobile
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShowmobileAddressBook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('showmobile_address_book');
        $this->hasColumn('label', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('street', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('suburb', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('city', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('zone_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('postal_code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShowmobileZone as Zone', array(
             'local' => 'zone_id',
             'foreign' => 'id'));

        $this->hasMany('ShowmobileVenue', array(
             'local' => 'id',
             'foreign' => 'address_book_id'));

        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}