<?php

/**
 * BaseShowmobilePassenger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $driver_id
 * @property sfGuardUser $User
 * @property ShowmobileDriver $Driver
 * 
 * @method integer             getUserId()    Returns the current record's "user_id" value
 * @method integer             getDriverId()  Returns the current record's "driver_id" value
 * @method sfGuardUser         getUser()      Returns the current record's "User" value
 * @method ShowmobileDriver    getDriver()    Returns the current record's "Driver" value
 * @method ShowmobilePassenger setUserId()    Sets the current record's "user_id" value
 * @method ShowmobilePassenger setDriverId()  Sets the current record's "driver_id" value
 * @method ShowmobilePassenger setUser()      Sets the current record's "User" value
 * @method ShowmobilePassenger setDriver()    Sets the current record's "Driver" value
 * 
 * @package    showmobile
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShowmobilePassenger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('showmobile_passenger');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('driver_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('ShowmobileDriver as Driver', array(
             'local' => 'driver_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}