<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/27 11:58:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sm',
  'username' => 'root',
  'password' => 'gatorade',
  'name' => 'doctrine',
)),);
