<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/11/27 11:01:47
sfConfig::add(array(
  'app_google_maps_api_keys' => array (
  'vendettasolutions.com' => 'ABQIAAAASKw2q9JwkwarpWHZaUj1XxRFzq3xA70_T-qIDxACVU0RthhjjBRmhbihMInczSNstu9zeO9Usr-qgQ',
  'sm.localhost' => 'ABQIAAAASKw2q9JwkwarpWHZaUj1XxShncN08UKHjcH4IgyDcq0zEEfMFhS1rOp1zJ1RV6NcrtNxgoIdddw5Nw',
),
  'app_ipinfodb_api_key' => 'd68b032ac3d090573a25a42aa48374ca917f9981440532b25ff262041238a830',
));
